package smoothfs

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"

	"github.com/google/uuid"
)

const DefaultMountBase = "/mnt/smoothfs"
const SystemdUnitDir = "/etc/systemd/system"

var poolNameRE = regexp.MustCompile(`^[a-z0-9][a-z0-9._-]{0,62}$`)

type CreateManagedPoolRequest struct {
	Name      string
	UUID      uuid.UUID
	Tiers     []string
	MountBase string
}

type ManagedPool struct {
	Name       string    `json:"name"`
	UUID       uuid.UUID `json:"uuid"`
	Tiers      []string  `json:"tiers"`
	Mountpoint string    `json:"mountpoint"`
	UnitPath   string    `json:"unit_path"`
}

func ValidatePoolName(name string) error {
	if !poolNameRE.MatchString(name) {
		return fmt.Errorf("invalid pool name %q: must match [a-z0-9][a-z0-9._-]{0,62}", name)
	}
	return nil
}

func ValidateTiers(tiers []string) error {
	if len(tiers) == 0 {
		return errors.New("at least one tier path required")
	}
	seen := make(map[string]struct{}, len(tiers))
	for _, t := range tiers {
		if !filepath.IsAbs(t) {
			return fmt.Errorf("tier path %q is not absolute", t)
		}
		if strings.ContainsAny(t, "\n\x00,:") {
			return fmt.Errorf("tier path %q contains a character forbidden in smoothfs tiers= (\\n, NUL, comma, colon)", t)
		}
		st, err := os.Stat(t)
		if err != nil {
			return fmt.Errorf("tier path %q: %w", t, err)
		}
		if !st.IsDir() {
			return fmt.Errorf("tier path %q is not a directory", t)
		}
		if _, dup := seen[t]; dup {
			return fmt.Errorf("duplicate tier path %q", t)
		}
		seen[t] = struct{}{}
	}
	return nil
}

func MountpointForPool(base, name string) string {
	if base == "" {
		base = DefaultMountBase
	}
	return filepath.Join(base, name)
}

func UnitFilenameFor(mountpoint string) string {
	trimmed := strings.TrimPrefix(mountpoint, "/")
	return strings.ReplaceAll(trimmed, "/", "-") + ".mount"
}

const mountUnitTemplate = `# smoothfs pool {{.Name}} — generated by tierd Phase 7.7.
# Edit via POST /api/smoothfs/pools or 'tierd-cli smoothfs
# create-pool' rather than hand-editing; hand-edited units are
# preserved on upgrade but any REST-driven change will rewrite
# this file.
[Unit]
Description=smoothfs pool {{.Name}}
Documentation=https://github.com/RakuenSoftware/smoothfs
After=local-fs-pre.target
Wants=local-fs-pre.target
# Smoothfs is a stacked filesystem over lower tier mountpoints;
# require all of them to be mounted first so the kernel's
# lower-path lookup succeeds on mount.
{{- range .RequiresMounts}}
Requires={{.}}
After={{.}}
{{- end}}

[Mount]
What=none
Where={{.Mountpoint}}
Type=smoothfs
Options=pool={{.Name}},uuid={{.UUID}},tiers={{.TierSpec}}

[Install]
WantedBy=local-fs.target
`

type unitVars struct {
	Name           string
	UUID           string
	Mountpoint     string
	TierSpec       string
	RequiresMounts []string
}

func RenderMountUnit(p ManagedPool) (string, error) {
	if err := ValidatePoolName(p.Name); err != nil {
		return "", err
	}
	if err := ValidateTiers(p.Tiers); err != nil {
		return "", err
	}
	reqs := make([]string, 0, len(p.Tiers))
	for _, t := range p.Tiers {
		reqs = append(reqs, UnitFilenameFor(t))
	}
	v := unitVars{
		Name:           p.Name,
		UUID:           p.UUID.String(),
		Mountpoint:     p.Mountpoint,
		TierSpec:       strings.Join(p.Tiers, ":"),
		RequiresMounts: reqs,
	}
	tmpl, err := template.New("unit").Parse(mountUnitTemplate)
	if err != nil {
		return "", fmt.Errorf("parse unit template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, v); err != nil {
		return "", fmt.Errorf("execute unit template: %w", err)
	}
	return buf.String(), nil
}

func CreateManagedPool(req CreateManagedPoolRequest) (*ManagedPool, error) {
	if err := ValidatePoolName(req.Name); err != nil {
		return nil, err
	}
	if err := ValidateTiers(req.Tiers); err != nil {
		return nil, err
	}
	poolUUID := req.UUID
	if poolUUID == uuid.Nil {
		poolUUID = uuid.New()
	}
	base := req.MountBase
	if base == "" {
		base = DefaultMountBase
	}
	mp := MountpointForPool(base, req.Name)
	pool := ManagedPool{
		Name:       req.Name,
		UUID:       poolUUID,
		Tiers:      req.Tiers,
		Mountpoint: mp,
		UnitPath:   filepath.Join(SystemdUnitDir, UnitFilenameFor(mp)),
	}

	if err := os.MkdirAll(mp, 0o755); err != nil {
		return nil, fmt.Errorf("mkdir mountpoint %s: %w", mp, err)
	}
	body, err := RenderMountUnit(pool)
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(pool.UnitPath, []byte(body), 0o644); err != nil {
		return nil, fmt.Errorf("write unit %s: %w", pool.UnitPath, err)
	}
	rollback := func() { _ = os.Remove(pool.UnitPath) }

	if err := runSystemctl("daemon-reload"); err != nil {
		rollback()
		return nil, fmt.Errorf("daemon-reload: %w", err)
	}
	if err := runSystemctl("enable", "--now", filepath.Base(pool.UnitPath)); err != nil {
		rollback()
		_ = runSystemctl("daemon-reload")
		return nil, fmt.Errorf("enable --now %s: %w", pool.UnitPath, err)
	}
	return &pool, nil
}

func DestroyManagedPool(p ManagedPool) error {
	unitName := filepath.Base(p.UnitPath)

	var firstErr error
	setErr := func(e error) {
		if firstErr == nil {
			firstErr = e
		}
	}

	if err := runSystemctl("disable", "--now", unitName); err != nil {
		setErr(fmt.Errorf("disable --now: %w", err))
	}
	if err := os.Remove(p.UnitPath); err != nil && !os.IsNotExist(err) {
		setErr(fmt.Errorf("remove unit: %w", err))
	}
	if err := runSystemctl("daemon-reload"); err != nil {
		setErr(fmt.Errorf("daemon-reload: %w", err))
	}
	return firstErr
}

var runSystemctl = func(args ...string) error {
	cmd := exec.Command("systemctl", args...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("systemctl %s: %s", strings.Join(args, " "), strings.TrimSpace(string(out)))
	}
	return nil
}
