#!/bin/bash
# enroll-signing-cert.sh — Phase 7.2 operator helper.
#
# Enrolls DKMS's default MOK signing certificate into the shim
# Machine Owner Key list so a secure-boot-enabled kernel will
# accept smoothfs.ko. Runs as root; needs mokutil (comes with
# shim-signed). After enrollment, the next reboot shows the shim
# MOK-management UI where the operator confirms the new key.
#
# The private key stays at /var/lib/dkms/mok.key and never leaves
# the build host. Only the public cert (/var/lib/dkms/mok.pub) is
# enrolled — that's the piece the kernel needs to verify
# signatures. MOK enrollment is a per-machine operation; each new
# appliance has its own autogenerated pair unless the operator
# drops in a pre-provisioned one.
#
# Usage:
#   enroll-signing-cert.sh               # enroll /var/lib/dkms/mok.pub
#   enroll-signing-cert.sh /path/to.pub  # enroll a specific cert
#   enroll-signing-cert.sh --status      # show current MOK list
#   enroll-signing-cert.sh --help

set -eu

CERT=${1:-/var/lib/dkms/mok.pub}

case "${1:-}" in
--help|-h)
	cat <<'EOF'
enroll-signing-cert.sh — Phase 7.2 MOK enrollment helper.

Enrolls DKMS's default signing certificate into the shim MOK list
so a secure-boot-enabled kernel will accept smoothfs.ko.

Usage:
  enroll-signing-cert.sh               enroll /var/lib/dkms/mok.pub
  enroll-signing-cert.sh /path/to.pub  enroll a specific cert
  enroll-signing-cert.sh --status      show current MOK list
  enroll-signing-cert.sh --help        this message

Requires root + mokutil (apt install shim-signed). After mokutil
--import, reboot the appliance and confirm the key at the shim
MOK-management prompt with the password you just entered.
EOF
	exit 0
	;;
--status)
	if ! command -v mokutil >/dev/null 2>&1; then
		echo "mokutil not installed — secure boot isn't supported on this system" >&2
		exit 1
	fi
	mokutil --list-enrolled
	echo "---"
	mokutil --list-new 2>/dev/null || true
	exit 0
	;;
esac

if [ "$(id -u)" != 0 ]; then
	echo "enroll-signing-cert: must run as root" >&2
	exit 1
fi

if ! command -v mokutil >/dev/null 2>&1; then
	echo "enroll-signing-cert: mokutil not installed" >&2
	echo "  apt install shim-signed" >&2
	exit 1
fi

if [ ! -r "$CERT" ]; then
	echo "enroll-signing-cert: $CERT not readable" >&2
	if [ "$CERT" = /var/lib/dkms/mok.pub ]; then
		echo "  DKMS auto-generates the pair on first module build." >&2
		echo "  Install smoothfs-dkms first, or run:" >&2
		echo "    dkms generate_mok" >&2
	fi
	exit 1
fi

echo "=== enrolling $CERT ==="
mokutil --import "$CERT"
cat <<'EOF'

Next steps:

  1. Reboot the appliance.
  2. At the shim MOK-management prompt, choose "Enroll MOK" and
     confirm with the password you just entered.
  3. After the reboot completes, run:
         bash /usr/share/smoothfs-dkms/module_signing.sh
     to confirm smoothfs loads under secure boot.

This is a one-time operation per appliance. Subsequent kernel
upgrades re-sign smoothfs with the same key on the build host;
the enrolled cert keeps verifying.
EOF
